# Generated by Django 2.0 on 2018-01-05 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_id', models.CharField(max_length=200, unique=True)),
                ('date_added_to_db', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_id', models.CharField(max_length=200, unique=True)),
                ('artist_id', models.CharField(max_length=200)),
                ('song_length', models.IntegerField()),
                ('date_added_to_lib', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_to_db', models.DateTimeField(default=django.utils.timezone.now)),
                ('artists', models.ManyToManyField(to='song_load.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('date_added_to_db', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='users_added',
            field=models.ManyToManyField(to='song_load.User'),
        ),
    ]
