# Generated by Django 2.0 on 2018-01-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_load', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_id',
        ),
    ]
