# Generated by Django 2.0 on 2018-01-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_load', '0002_remove_song_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.CharField(default='url', max_length=200),
        ),
    ]
