# Generated by Django 2.0 on 2018-01-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_load', '0004_auto_20180106_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.CharField(default='url', max_length=200),
        ),
    ]
