# Generated by Django 2.0 on 2018-01-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_load', '0008_auto_20180106_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
